# Generated by Django 4.0.4 on 2022-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=1000)),
                ('parent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('vender_id', models.IntegerField()),
                ('users_id', models.IntegerField()),
                ('order_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('image_url1', models.CharField(default='https://imgs.search.brave.com/Wmgf1m-wbgzOgdfoZcSGBb5C7baYyA-_V99Okq6dyro/rs:fit:256:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5m/TWVtTUdKTklQZDVm/TFRJNlR3SndRSGFI/YSZwaWQ9QXBp', max_length=300)),
                ('image_url2', models.CharField(default='https://imgs.search.brave.com/Wmgf1m-wbgzOgdfoZcSGBb5C7baYyA-_V99Okq6dyro/rs:fit:256:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5m/TWVtTUdKTklQZDVm/TFRJNlR3SndRSGFI/YSZwaWQ9QXBp', max_length=300)),
                ('vender_id', models.IntegerField()),
                ('reveiw', models.CharField(default='none', max_length=400)),
                ('related_products', models.CharField(default='none', max_length=50)),
                ('product_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('preference', models.CharField(default='none', max_length=200)),
                ('history', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('products', models.CharField(max_length=500)),
                ('image_url', models.CharField(default='https://imgs.search.brave.com/Wmgf1m-wbgzOgdfoZcSGBb5C7baYyA-_V99Okq6dyro/rs:fit:256:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5m/TWVtTUdKTklQZDVm/TFRJNlR3SndRSGFI/YSZwaWQ9QXBp', max_length=300)),
            ],
        ),
    ]
