# Generated by Django 4.0.4 on 2022-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vender',
            name='address',
            field=models.TextField(),
        ),
    ]
