# Generated by Django 4.0.4 on 2022-07-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_comments_text_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_time',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='products',
            name='date_time',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
