# Generated by Django 4.0.4 on 2022-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_chat_date_time_comments_date_time_orders_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
