# Generated by Django 4.0.4 on 2022-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_users_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='lat_longitude',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='pin_code',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='vender',
            name='city',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='vender',
            name='lat_longitude',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='vender',
            name='pin_code',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='vender',
            name='state',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
