# Generated by Django 4.0.4 on 2022-08-13 10:29

from django.db import migrations, models
import django.db.models.deletion
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_users_city_users_lat_longitude_users_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.products'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lat_longitude',
            field=models.CharField(default='none', max_length=30, validators=[main_app.validators.validate_lat_longitude]),
        ),
        migrations.AlterField(
            model_name='users',
            name='pin_code',
            field=models.CharField(default='none', max_length=10, validators=[main_app.validators.validate_pincode]),
        ),
    ]
