# Generated by Django 4.0.4 on 2022-08-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_comments_parent_alter_users_lat_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vender_id',
        ),
        migrations.RemoveField(
            model_name='vender',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='vender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.vender'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lat_longitude',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='pin_code',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='vender',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.CreateModel(
            name='product_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.IntegerField()),
                ('product', models.ManyToManyField(to='main_app.products')),
            ],
        ),
    ]
