# Generated by Django 4.0.4 on 2022-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_product_class_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_url1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_url2',
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
