# Generated by Django 4.0.4 on 2022-08-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_products_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date_time',
        ),
    ]
