# Generated by Django 4.0.4 on 2022-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_chat_vender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.products'),
        ),
    ]
