# Generated by Django 4.0.4 on 2022-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_users_cart_users_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_class',
            name='class_img_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
