# Generated by Django 4.0.4 on 2022-09-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_product_class_class_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_class',
            name='class_img_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
