# Generated by Django 4.0.4 on 2022-09-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_product_class_class_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AlterField(
            model_name='product_class',
            name='class_img_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='imges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.products')),
            ],
        ),
    ]
