# Generated by Django 4.0.4 on 2022-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_products_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
