# Generated by Django 4.0.4 on 2022-09-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_products_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_class',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='pclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.product_class'),
        ),
    ]
