# Generated by Django 4.0.4 on 2022-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_remove_product_class_product_products_pclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pclass',
        ),
        migrations.AddField(
            model_name='products',
            name='pclass',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.product_class'),
        ),
    ]
