# Generated by Django 4.0.4 on 2022-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_remove_products_pclass_products_pclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
