# Generated by Django 4.0.4 on 2022-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_products_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_class',
            name='class_img_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
