# Generated by Django 4.0.4 on 2022-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_remove_users_history_remove_users_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.CharField(default='', max_length=30),
        ),
    ]
