# Generated by Django 4.0.4 on 2022-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_comments_rating_products_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='average_ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
