# Generated by Django 4.0.4 on 2022-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_comments_average_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='average_ratings',
        ),
        migrations.AddField(
            model_name='products',
            name='average_ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='products',
            name='no_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
