# Generated by Django 4.0.4 on 2022-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_comments_average_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='reviews',
            field=models.CharField(default='0,0,0,0,0', max_length=30),
        ),
    ]
