# Generated by Django 4.0.4 on 2022-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_products_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='average_ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
