# Generated by Django 4.0.4 on 2022-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_products_average_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
