# Generated by Django 4.0.4 on 2022-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_vender_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
