# Generated by Django 4.0.4 on 2022-09-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_alter_vender_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vender',
            name='phone',
        ),
    ]
